### ISSUE TITLE
Online ordering price updates

### ISSUE THREAD

**Issue by Jeanie825** [genson-softworks/personalchef#2]
Online ordering app updates:
Tilapia price
Small - $7.99 (from $7.49)
Large - $9.99 (i.e. + $2.00 to small price)

Ground turkey
Small - $7.99
Large - $9.89 (i.e. + $1.90 to small price)

Ground beef
Small - $7.99
Large - $9.89 (i.e. + $1.90 to small price)

Traditional Breakfast
Small $5.75
Large $7.75 (i.e. + $2.00 to small price)

Chicken grilled
Large - $8.99 (i.e. + $2.00 to small price)

Chicken - slow roasted
Large - $8.99 (i.e. + $2.00 to small price)

Small chicken dinners (grilled & slow roasted) are same price as before.

**Comment by jerradgenson** [comment]
Got these prices updates on the online ordering site. I also added a new item titled "Grilled Chicken" — I don't have a picture for that, so if you want one, please post it in the comments here. I'm closing the issue for now.

**Comment by Jeanie825** [comment]
Thank you!
