### ISSUE TITLE
Funds not received from Stripe 5/31/17 4:49 pm transaction

### ISSUE THREAD

**Issue by Jeanie825** [genson-softworks/personalchef#3]
Received an order from Scott Sanders on May 31 at 4:49 pm for $72.96.  Reflects 'Online payment done', order was filled yesterday and picked up by customer; however, funds have not yet been credited to our account.  Understand you may not have time to contact them with other responsibilities but if you do that's great.  If not, am I listed on the account and do you have contact info?  Thank you!

**Comment by jerradgenson** [comment]
Looks like Stripe authorized the transaction, but didn't automatically capture it. I initiated the capture manually and it appears to have succeeded. I believe this resolves the issue, and the payment should appear in your account on Tuesday. If it doesn't, we can reopen it then.
